name: 'Setup Strong-Opx'
description: 'Install and Configure Strong-OpX'
inputs:
  version:
    description: 'Strong-OpX version to use. If not provided, the version of the action will be used.'
    default: ''
  python-version:
    description: 'Python version to use'
    default: '3.12'
  project-path:
    description: 'Project path'
    required: true
  ssh-user:
    description: 'SSH username'
    default: ''
  ssh-key:
    description: 'SSH key'
    default: ''
  git-ssh-key:
    description: 'SSH key to use for pulling source code during deployment'
    default: ''
outputs:
  executable:
    description: 'strong-opx executable path'
    value: ${{ steps.path.outputs.executable-path }}
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.python-version }}"

    - name: Extract version tag from action reference
      id: get-version
      run: |
        if [ -z "${{ inputs.version }}" ]; then
          # Extract version from github.action_ref (e.g., v1.2 from strongio/strong-opx@v1.2)
          VERSION=$(echo "${{ github.action_ref }}" | sed 's/^v//')
        else
          VERSION="${{ inputs.version }}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: cache venv
      id: cache
      uses: actions/cache@v3
      with:
        path: /opt/strong-opx
        key: "strong-opx-${{ steps.get-version.outputs.version }}"

    - name: create venv
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: python -m venv /opt/strong-opx

    - name: set env vars
      shell: bash
      run: |
        source /opt/strong-opx/bin/activate
        echo "PATH=$PATH" >> $GITHUB_ENV

    - name: install strong-opx
      shell: bash
      run: |
        source /opt/strong-opx/bin/activate
        if [ "${{ github.action_ref }}" = "master" ] && [ -z "${{ inputs.version }}" ]; then
          pip install strong-opx
        else
          pip install "strong-opx==${{ steps.get-version.outputs.version }}"
        fi

    - name: register project
      shell: bash
      run: strong-opx project register "${{ inputs.project-path }}"

    - name: configure ssh for strong-opx
      if: ${{ inputs.ssh-key }}
      shell: bash
      run: |
        install -m 700 -d ~/.ssh
        install -m 644 /dev/null ~/.ssh/config
        install -m 600 <(echo "${{ inputs.ssh-key }}") ~/.ssh/strong-opx-ssh
        printf "Host *\n\tStrictHostKeyChecking no" >> ~/.ssh/config

        strong-opx config ssh.user ${{ inputs.ssh-user }}
        strong-opx config ssh.key ~/.ssh/strong-opx-ssh

    - name: configure git credentials for strong-opx
      if: ${{ inputs.git-ssh-key }}
      shell: bash
      run: |
        install -m 600 <(echo "${{ inputs.git-ssh-key }}") ~/.ssh/strong-opx-git-ssh
        strong-opx config git.ssh.key ~/.ssh/strong-opx-git-ssh

    - name: get strong-opx executable path
      id: path
      shell: bash
      run: echo "executable-path=$(which strong-opx)" >> $GITHUB_OUTPUT
